In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.simplefilter("ignore")

In [2]:
movies_data=pd.read_csv('anime.csv')
movies_data.head(3)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262

In [3]:
movies_data.reset_index(inplace=True)
movies_data.head(2)

,index,anime_id,name,genre,type,episodes,rating,members
0,0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665

In [4]:
movies_data.shape

(12294, 8)

In [5]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     12294 non-null  int64
 1   anime_id  12294 non-null  int64
 2   name      12294 non-null  object
 3   genre     12232 non-null  object
 4   type      12269 non-null  object
 5   episodes  12294 non-null  object
 6   rating    12064 non-null  float64
 7   members   12294 non-null  int64
dtypes: float64(1), int64(3), object(4)
memory usage: 768.5+ KB

In [6]:
movies_data.isnull().sum()

index         0
anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [7]:
# selecting the relevant features for recommendation

selected_features = ['genre','type','rating']
print(selected_features)

['genre', 'type', 'rating']

In [8]:
# replacing the null valuess with null string

for features in selected_features:
    movies_data[features]=movies_data[features].fillna('')

In [9]:
# combining all the 5 selected features

combined_features = movies_data['genre']+' '+movies_data['type']

In [10]:
print(combined_features)

0               Drama, Romance, School, Supernatural Movie
1        Action, Adventure, Drama, Fantasy, Magic, Mili...
2        Action, Comedy, Historical, Parody, Samurai, S...
3                                      Sci-Fi, Thriller TV
4        Action, Comedy, Historical, Parody, Samurai, S...
                               ...
12289                                           Hentai OVA
12290                                           Hentai OVA
12291                                           Hentai OVA
12292                                           Hentai OVA
12293                                         Hentai Movie
Length: 12294, dtype: object

### Convert the Text Data into Vectors

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
feature_vectors=vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 8)	0.4064272010487408
  (0, 34)	0.4527152773385316
  (0, 36)	0.47908849608944204
  (0, 46)	0.5025939149322276
  (0, 24)	0.384368804014889
  (1, 8)	0.3249918844190286
  (1, 0)	0.2851370263052738
  (1, 1)	0.3073533011726408
  (1, 10)	0.3092912941250856
  (1, 20)	0.4351161402236701
  (1, 23)	0.5047112391013231
  (1, 40)	0.3396562864271053
  (1, 48)	0.2520399009293464
  (2, 0)	0.2446984961974193
  (2, 40)	0.2914857589337753
  (2, 48)	0.21629525122818785
  (2, 5)	0.19601345139698537
  (2, 15)	0.36989945843667305
  (2, 30)	0.4374107864568645
  (2, 35)	0.5377197655779328
  (2, 37)	0.2762765260670507
  (2, 11)	0.2762765260670507
  (3, 48)	0.29229640552335473
  (3, 37)	0.3733537146161548
  (3, 11)	0.3733537146161548
  :	:
  (12282, 14)	0.8251404752084168
  (12283, 29)	0.5649276025941982
  (12283, 14)	0.8251404752084168
  (12284, 29)	0.5649276025941982
  (12284, 14)	0.8251404752084168
  (12285, 46)	0.4853519692839578
  (12285, 29)	0.32315453904991537
  (12285, 7)	0.661223990047087
  (12285, 14)	0.47200364912766357
  (12286, 29)	0.5649276025941982
  (12286, 14)	0.8251404752084168
  (12287, 29)	0.5649276025941982
  (12287, 14)	0.8251404752084168
  (12288, 29)	0.5649276025941982
  (12288, 14)	0.8251404752084168
  (12289, 29)	0.5649276025941982
  (12289, 14)	0.8251404752084168
  (12290, 29)	0.5649276025941982
  (12290, 14)	0.8251404752084168
  (12291, 29)	0.5649276025941982
  (12291, 14)	0.8251404752084168
  (12292, 29)	0.5649276025941982
  (12292, 14)	0.8251404752084168
  (12293, 24)	0.6181537454576116
  (12293, 14)	0.7860572160960845

### Cosine Similarity

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.13208554 0.         ... 0.         0.         0.23759902]
 [0.13208554 1.         0.22329261 ... 0.         0.         0.        ]
 [0.         0.22329261 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         1.         0.64860762]
 [0.         0.         0.         ... 1.         1.         0.64860762]
 [0.23759902 0.         0.         ... 0.64860762 0.64860762 1.        ]]

In [13]:
print(similarity.shape)

(12294, 12294)

In [14]:
# creating a list with all the movie names given in the dataset

list_of_all_titles=movies_data['name'].tolist()
print(list_of_all_titles)

['Kimi no Na wa.', 'Fullmetal Alchemist: Brotherhood', 'Gintama°', 'Steins;Gate', 'Gintama&#039;', 'Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou', 'Hunter x Hunter (2011)', 'Ginga Eiyuu Densetsu', 'Gintama Movie: Kanketsu-hen - Yorozuya yo Eien Nare', 'Gintama&#039;: Enchousen', 'Clannad: After Story', 'Koe no Katachi', 'Gintama', 'Code Geass: Hangyaku no Lelouch R2', 'Haikyuu!! Second Season', 'Sen to Chihiro no Kamikakushi', 'Shigatsu wa Kimi no Uso', 'Mushishi Zoku Shou 2nd Season', 'Ookami Kodomo no Ame to Yuki', 'Code Geass: Hangyaku no Lelouch', 'Hajime no Ippo', 'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen', 'Cowboy Bebop', 'One Punch Man', 'Mononoke Hime', 'Suzumiya Haruhi no Shoushitsu', 'Monogatari Series: Second Season', 'Mushishi Zoku Shou', 'Mushishi', 'Tengen Toppa Gurren Lagann', 'Great Teacher Onizuka', 'Natsume Yuujinchou Go', 'Hajime no Ippo: New Challenger', 'Mushishi Zoku Shou: Suzu no Shizuku', 'Natsume Yuujinchou Shi', 'Howl no Ugoku Shiro', 'Fate/Zero 2nd Season', 'Kizumonogatari II: Nekketsu-hen', 'Monster', 'Bakuman. 3rd Season', 'Death Note', 'Gintama°: Aizome Kaori-hen', 'Ansatsu Kyoushitsu (TV) 2nd Season', 'Haikyuu!!', 'Hajime no Ippo: Rising', 'Kara no Kyoukai 5: Mujun Rasen', 'Natsume Yuujinchou San', 'Ping Pong The Animation', 'Mushishi Special: Hihamukage', 'Boku dake ga Inai Machi', 'Yojouhan Shinwa Taikei', 'Aria The Origination', 'Kamisama Hajimemashita: Kako-hen', 'Rainbow: Nisha Rokubou no Shichinin', 'Re:Zero kara Hajimeru Isekai Seikatsu', 'Tengen Toppa Gurren Lagann Movie: Lagann-hen', 'Zoku Natsume Yuujinchou', 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.', 'Kuroko no Basket 3rd Season', 'Steins;Gate Movie: Fuka Ryouiki no Déjà vu', 'Hotarubi no Mori e', 'Shokugeki no Souma', 'Yuri!!! on Ice', 'Gintama: Yorinuki Gintama-san on Theater 2D', 'JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season', 'Gintama Movie: Shinyaku Benizakura-hen', 'Hellsing Ultimate', 'Kiseijuu: Sei no Kakuritsu', 'Shouwa Genroku Rakugo Shinjuu', 'Uchuu Kyoudai', 'Bakemono no Ko', 'Hotaru no Haka', 'Kuroko no Basket 2nd Season', 'Major S5', 'One Piece', 'Ghost in the Shell: Stand Alone Complex 2nd GIG', 'JoJo no Kimyou na Bouken: Diamond wa Kudakenai', 'Kara no Kyoukai 7: Satsujin Kousatsu (Kou)', 'Kingdom 2nd Season', 'Slam Dunk', 'Usagi Drop', 'Girls und Panzer der Film', 'Mob Psycho 100', 'Nana', 'Baccano!', 'Mushishi Zoku Shou: Odoro no Michi', 'Shingeki no Kyojin', 'Bakuman. 2nd Season', 'Cross Game', 'Doukyuusei (Movie)', 'Evangelion: 2.0 You Can (Not) Advance', 'Shinsekai yori', 'Uchuu Senkan Yamato 2199', 'Chihayafuru 2', 'Fate/Zero', 'JoJo no Kimyou na Bouken (TV)', 'Mahou Shoujo Madoka★Magica', 'Nichijou', 'Psycho-Pass', 'Barakamon', 'Diamond no Ace: Second Season', 'Magi: The Kingdom of Magic', 'Mahou Shoujo Madoka★Magica Movie 3: Hangyaku no Monogatari', 'Major: World Series', 'Samurai Champloo', 'Shokugeki no Souma: Ni no Sara', 'Katanagatari', 'Mahou Shoujo Madoka★Magica Movie 2: Eien no Monogatari', 'Major S6', 'Mononoke', 'Shirobako', 'Ashita no Joe 2', 'Hunter x Hunter', 'Noragami Aragoto', 'Sakamichi no Apollon', 'Tonari no Totoro', 'Ghost in the Shell: Stand Alone Complex', 'Kaze no Tani no Nausicaä', 'No Game No Life', 'Romeo no Aoi Sora', 'Yuu☆Yuu☆Hakusho', 'Kino no Tabi: The Beautiful World', 'Kuroko no Basket', 'Nodame Cantabile', 'Ookami to Koushinryou II', 'Shingeki no Kyojin: Kuinaki Sentaku', 'Steins;Gate: Oukoubakko no Poriomania', 'Fate/stay night: Unlimited Blade Works 2nd Season', 'Kemono no Souja Erin', 'Kizumonogatari I: Tekketsu-hen', 'Neon Genesis Evangelion: The End of Evangelion', 'Toradora!', 'Toki wo Kakeru Shoujo', 'Tsubasa: Tokyo Revelations', 'Owarimonogatari', 'Rurouni Kenshin: Meiji Kenkaku Romantan', 'Stranger: Mukou Hadan', 'Detective Conan Movie 06: The Phantom of Baker Street', 'Fate/stay night: Unlimited Blade Works', 'Major S1', 'Mobile Suit Gundam: The Origin', 'Nanatsu no Taizai', 'Natsume Yuujinchou', 'One Piece Film: Strong World', 'Higurashi no Naku Koro ni Kai', 'Hunter x Hunter OVA', 'Hunter x Hunter: Greed Island Final', 'Kuroshitsuji: Book of Murder', 'Major S2', 'One Outs', 'Beck', 'Berserk', 'Cowboy Bebop: Tengoku no Tobira', 'Major S3', 'Mobile Suit Gundam Unicorn', 'Natsume Yuujinchou: Itsuka Yuki no Hi ni', 'NHK ni Youkoso!', 'Rose of Versailles', 'Sakurasou no Pet na Kanojo', 'Angel Beats!', 'Bakemonogatari', 'Bungou Stray Dogs 2nd Season', 'Hajime no Ippo: Champion Road', 'One Piece Film: Z', 'Ouran Koukou Host Club', 'Detective Conan Movie 13: The Raven Chaser', 'Durarara!!', 'Nodame Cantabile Finale', 'Planetes', 'Shelter', 'Tenkuu no Shiro Laputa', 'Gintama: Shiroyasha Koutan', 'Hachimitsu to Clover II', 'InuYasha: Kanketsu-hen', 'Kaguya-hime no Monogatari', 'Katekyo Hitman Reborn!', 'Kuroshitsuji: Book of Circus', 'Ookami to Koushinryou', 'Boku no Hero Academia', 'Gin no Saji 2nd Season', 'Little Busters!: Refrain', 'Major: Message', 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2', 'SKET Dance', 'Bakuman.', 'Danshi Koukousei no Nichijou', 'Kotonoha no Niwa', 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Mirai-hen', 'Major S4', 'Omoide no Marnie', 'Working!!!: Lord of the Takanashi', 'Ghost in the Shell', 'K-On! Movie', 'Kuroko no Basket: Saikou no Present Desu', 'Mahou Shoujo Lyrical Nanoha: The Movie 2nd A&#039;s', 'Sennen Joyuu', 'Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero', 'xxxHOLiC Kei', 'Berserk: Ougon Jidai-hen III - Kourin', 'Death Parade', 'Fullmetal Alchemist', 'Gyakkyou Burai Kaiji: Ultimate Survivor', 'Hunter x Hunter: Greed Island', 'Redline', 'Chihayafuru', 'Detective Conan Movie 20: The Darkest Nightmare', 'Dragon Ball Z', 'Fate/stay night: Unlimited Blade Works - Prologue', 'Kokoro ga Sakebitagatterunda.', 'Mimi wo Sumaseba', 'Nagi no Asukara', 'Neon Genesis Evangelion', 'One Piece Film: Gold', 'Tokyo Godfathers', 'Trigun', 'xxxHOLiC Rou', 'Gintama: Shinyaku Benizakura-hen', 'Mahou Shoujo Madoka★Magica Movie 1: Hajimari no Monogatari', 'Sekaiichi Hatsukoi 2', 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku', 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku OVA', 'Aria The Natural', 'Black Lagoon: The Second Barrage', 'Clannad', 'Kami nomi zo Shiru Sekai: Megami-hen', 'Summer Wars', 'Baccano! Specials', 'Detective Conan Movie 14: The Lost Ship in the Sky', 'Gyakkyou Burai Kaiji: Hakairoku-hen', 'Initial D Final Stage', 'Kaiba', 'One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari', 'Saiki Kusuo no Ψ-nan (TV)', 'Cardcaptor Sakura Movie 2: Fuuin Sareta Card', 'Hajime no Ippo: Mashiba vs. Kimura', 'Kamisama Hajimemashita◎', 'Skip Beat!', 'Yowamushi Pedal: Grande Road', 'Gankutsuou', 'Majo no Takkyuubin', 'Nodame Cantabile: Paris-hen', 'One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna', 'Osomatsu-san', 'Space☆Dandy 2nd Season', 'Tsumiki no Ie', 'Detroit Metal City', 'Eve no Jikan', 'Eve no Jikan (Movie)', 'Kaichou wa Maid-sama!', 'Saint Seiya: Meiou Hades Juuni Kyuu-hen', 'Zankyou no Terror', 'Darker than Black: Kuro no Keiyakusha', 'Detective Conan', 'Detective Conan Movie 05: Countdown to Heaven', 'Diamond no Ace', 'Fairy Tail (2014)', 'Hibike! Euphonium 2', 'JoJo no Kimyou na Bouken: Stardust Crusaders', 'Maison Ikkoku', 'Non Non Biyori Repeat', 'Shijou Saikyou no Deshi Kenichi', 'Yuusha-Ou GaoGaiGar Final', 'Gekkan Shoujo Nozaki-kun', 'Initial D Fourth Stage', 'Junjou Romantica 2', 'Kaze Tachinu', 'Kingdom', 'Kuragehime', 'Magi: The Labyrinth of Magic', 'Mobile Suit Gundam 00', 'ReLIFE', 'Saint Seiya: The Lost Canvas - Meiou Shinwa', 'Seirei no Moribito', 'Akatsuki no Yona', 'Detective Conan Movie 08: Magician of the Silver Sky', 'Durarara!!x2 Ketsu', 'Free!: Eternal Summer Special', 'Glass no Kamen (2005)', 'Gosick', 'Hajime no Ippo: Boxer no Kobushi', 'Initial D First Stage', 'Kill la Kill', 'Lovely★Complex', 'Perfect Blue', 'Princess Tutu', 'Sakasama no Patema', 'Tsubasa: Shunraiki', 'Ashita no Joe', 'Fairy Tail', 'Ghost in the Shell: Stand Alone Complex - Solid State Society', 'Magi: Sinbad no Bouken (TV)', 'Shoujo Kakumei Utena', 'Tengen Toppa Gurren Lagann Movie: Gurren-hen', 'Detective Conan Movie 10: Requiem of the Detectives', 'Evangelion: 1.0 You Are (Not) Alone', 'Full Metal Panic? Fumoffu', 'Ginga Eiyuu Densetsu: Arata Naru Tatakai no Overture', 'Kara no Kyoukai 3: Tsuukaku Zanryuu', 'Mobile Suit Gundam 00 Second Season', 'Nisemonogatari', 'Tsukimonogatari', 'Ansatsu Kyoushitsu (TV)', 'Aria The Avvenire', 'Baby Steps 2nd Season', 'D.Gray-man', 'Ginga Eiyuu Densetsu Gaiden: Senoku no Hoshi, Senoku no Hikari', 'Gintama: Jump Festa 2014 Special', 'Lupin III: Cagliostro no Shiro', 'Mobile Suit Gundam: Iron-Blooded Orphans 2nd Season', 'Ookiku Furikabutte: Natsu no Taikai-hen', 'Saiunkoku Monogatari 2nd Season', 'Sekaiichi Hatsukoi Movie: Yokozawa Takafumi no Baai', 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai. Movie', 'Dennou Coil', 'Eureka Seven', 'Ghost in the Shell: Stand Alone Complex - The Laughing Man', 'Gintama: Dai Hanseikai', 'Hidamari Sketch: Sae Hiro Sotsugyou-hen', 'Hikaru no Go', 'Kimi ni Todoke', 'Kokoro Connect: Michi Random', 'Tokyo Magnitude 8.0', 'Cardcaptor Sakura', 'ef: A Tale of Melodies.', 'Gin no Saji', 'Hachimitsu to Clover', 'Kodomo no Omocha (TV)', 'Love Live! The School Idol Movie', 'Mahoutsukai no Yome: Hoshi Matsu Hito', 'Sekaiichi Hatsukoi OVA', 'Working!!!', 'Black Lagoon', 'Detective Conan Movie 18: The Sniper from Another Dimension', 'Final Fantasy VII: Advent Children Complete', 'Higurashi no Naku Koro ni', 'Hyouka', 'Interstella5555: The 5tory of The 5ecret 5tar 5ystem', 'Kanon (2006)', 'Kimi ni Todoke 2nd Season', 'Noragami', 'Persona 3 the Movie 4: Winter of Rebirth', 'xxxHOLiC Shunmuki', 'Zetsuen no Tempest', 'Aria The Origination: Sono Choppiri Himitsu no Basho ni...', 'Detective Conan Movie 03: The Last Wizard of the Century', 'Detective Conan Movie 04: Captured in Her Eyes', 'Dragon Ball', 'Hanada Shounen-shi', 'Junjou Romantica 3', 'Juuni Kokuki', 'Major Movie: Yuujou no Winning Shot', 'Mirai Shounen Conan', 'One Piece Film: Strong World Episode 0', 'Phantom: Requiem for the Phantom', 'Tamako Love Story', 'Toaru Kagaku no Railgun S', 'Touch', 'Yowamushi Pedal', 'Akira', 'Black Lagoon: Roberta&#039;s Blood Trail', 'Durarara!!x2 Shou', 'Gintama: Jump Festa 2015 Special', 'High☆Speed!: Free! Starting Days', 'Kyou kara Ore wa!!', 'Nurarihyon no Mago: Sennen Makyou', 'Paprika', 'Prince of Tennis: The National Tournament Finals', 'School Rumble Ni Gakki', 'Sekaiichi Hatsukoi', 'Akagami no Shirayuki-hime 2nd Season', 'Clannad: Mou Hitotsu no Sekai, Tomoyo-hen', 'Ginga Nagareboshi Gin', 'Initial D Fifth Stage', 'K-On!!', 'Log Horizon', 'Sekaiichi Hatsukoi: Valentine-hen', 'Slayers Next', 'Aria The OVA: Arietta', 'Detective Conan Movie 15: Quarter of Silence', 'Digimon Adventure tri. 3: Kokuhaku', 'Gintama: Nanigoto mo Saiyo ga Kanjin nano de Tasho Senobisuru Kurai ga Choudoyoi', 'Igano Kabamaru', 'Kamisama Hajimemashita', 'Kara no Kyoukai: Mirai Fukuin', 'Mobile Suit Gundam: The 08th MS Team', 'Omae Umasou da na', 'Ushio to Tora (TV) 2nd Season', 'Wolf&#039;s Rain OVA', 'Ajin 2nd Season', 'Aoki Hagane no Arpeggio: Ars Nova Cadenza', 'City Hunter 2', 'Durarara!!x2 Ten', 'ef: A Tale of Memories.', 'Ghost in the Shell 2.0', 'Ghost in the Shell: Stand Alone Complex 2nd GIG - Individual Eleven', 'Ginga Sengoku Gunyuuden Rai', 'Initial D Second Stage', 'Kami nomi zo Shiru Sekai II', 'Noragami Aragoto OVA', 'Stand By Me Doraemon', 'Tiger &amp; Bunny', 'Yahari Ore no Seishun Love Comedy wa Machigatteiru.', 'Fullmetal Alchemist: Brotherhood Specials', 'Hanamonogatari', 'Kimi to Boku. 2', 'Ookiku Furikabutte', 'Ore Monogatari!!', 'Tamayura: Sotsugyou Shashin Part 4 - Ashita', 'Tekkon Kinkreet', 'There She Is!!', 'xxxHOLiC', 'Byousoku 5 Centimeter', 'Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen', 'Ginga Eiyuu Densetsu Gaiden: Rasen Meikyuu', 'Hyouge Mono', 'Karigurashi no Arrietty', 'Mahou Shoujo Lyrical Nanoha A&#039;s', 'Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou-hen', 'Tanaka-kun wa Itsumo Kedaruge', 'Berserk: Ougon Jidai-hen II - Doldrey Kouryaku', 'Darker than Black: Kuro no Keiyakusha Gaiden', 'Elsword: El Lady', 'Ginga Eiyuu Densetsu: Waga Yuku wa Hoshi no Taikai', 'Hikaru no Go: Journey to the North Star Cup', 'Hybrid Child', 'Isekai no Seikishi Monogatari', 'Junjou Romantica OVA', 'Kobato.', 'Kuuchuu Buranko', 'Macross: Do You Remember Love?', 'One Piece 3D2Y: Ace no shi wo Koete! Luffy Nakama Tono Chikai', 'Prince of Tennis: The National Tournament', 'Prince of Tennis: The National Tournament Semifinals', 'Eyeshield 21', 'Full Moon wo Sagashite', 'Grisaia no Rakuen', 'Jigoku Shoujo Futakomori', 'Junjou Romantica', 'Mawaru Penguindrum', 'SKET Dance OVA', 'Soul Eater', 'Trigun: Badlands Rumble', 'Haibane Renmei', 'Kuroko no Basket: Tip Off', 'Macross', 'Mirai Nikki (TV)', 'Saiyuuki Reload: Burial', 'Tentai Senshi Sunred 2nd Season', 'Terra e... (TV)', 'Tokyo Ghoul', 'Usagi Drop Specials', 'Yume-iro Pâtissière', 'Azumanga Daioh', 'Colorful (Movie)', 'Detective Conan OVA 09: The Stranger in 10 Years...', 'Drifters: Special Edition', 'FLCL', 'Full Metal Panic! The Second Raid', 'Kuroshitsuji', 'Love Live! School Idol Project 2nd Season', 'Macross F Movie 2: Sayonara no Tsubasa', 'Magi: Sinbad no Bouken', 'Nekomonogatari: Kuro', 'Saiunkoku Monogatari', 'School Rumble', 'Strike the Blood II', 'Suzumiya Haruhi no Yuuutsu', 'Flanders no Inu (Movie)', 'Golden Boy', 'Grisaia no Meikyuu: Caprice no Mayu 0', 'Kaleido Star', 'Kara no Kyoukai 4: Garan no Dou', 'Lupin III vs. Detective Conan: The Movie', 'Non Non Biyori', 'Seitokai Yakuindomo* OVA', 'Yakitate!! Japan', 'Beelzebub', 'Death Billiards', 'Durarara!! Specials', 'Jormungand: Perfect Order', 'Mahou Shoujo Lyrical Nanoha: The Movie 1st', 'Overlord', 'Prince of Tennis', 'Takarajima', 'xxxHOLiC Movie: Manatsu no Yoru no Yume', 'Yuru Yuri San☆Hai!', 'Boruto: Naruto the Movie', 'Coquelicot-zaka kara', 'Eikoku Koi Monogatari Emma: Molders-hen', 'Ergo Proxy', 'Hanasaku Iroha', 'Hataraku Maou-sama!', 'Hibike! Euphonium', 'Higashi no Eden', 'Ie Naki Ko Remi', 'Kono Subarashii Sekai ni Shukufuku wo!', 'Kurenai no Buta', 'Mobile Suit Zeta Gundam', 'Prison School', 'Saint Seiya', 'Sayonara Zetsubou Sensei', 'Seto no Hanayome OVA', 'Zoku Sayonara Zetsubou Sensei', 'Akachan to Boku', 'Clannad: After Story - Mou Hitotsu no Sekai, Kyou-hen', 'Hakuouki Movie 2: Shikon Soukyuu', 'Kara no Kyoukai 2: Satsujin Kousatsu (Zen)', 'Macross F', 'Magic Kaito', 'Sakigake!! Cromartie Koukou', 'Shijou Saikyou no Deshi Kenichi OVA', 'Touhai Densetsu Akagi: Yami ni Maiorita Tensai', 'Carnival Phantasm', 'D.Gray-man Hallow', 'Date A Live: Encore OVA', 'Dragon Ball Kai (2014)', 'Gochuumon wa Usagi Desu ka??', 'Hidamari Sketch x ☆☆☆', 'Kokoro Connect', 'Saiyuuki Gaiden', 'Shirokuma Cafe', 'Tiger &amp; Bunny Movie 2: The Rising', 'Zan Sayonara Zetsubou Sensei', 'City Hunter', 'Detective Conan Movie 02: The Fourteenth Target', 'Gekkan Shoujo Nozaki-kun Specials', 'Giant Robo the Animation: Chikyuu ga Seishi Suru Hi', 'Hetalia: The Beautiful World Specials', 'Kaleido Star: Legend of Phoenix - Layla Hamilton Monogatari', 'Kamisama Hajimemashita OVA', 'Little Witch Academia', 'Maria-sama ga Miteru 3rd', 'Mobile Suit Gundam Thunderbolt', 'The Everlasting Guilty Crown', 'Bishoujo Senshi Sailor Moon: Sailor Stars', 'Break Blade 4: Sanka no Chi', 'Hanasaku Iroha: Home Sweet Home', 'Hidamari Sketch x Honeycomb', 'Hokuto no Ken', 'Les Misérables: Shoujo Cosette', 'Serial Experiments Lain', 'Shiki', 'Ushiro no Shoumen Daare', 'Baka to Test to Shoukanjuu Ni!', 'Detective Conan Movie 01: The Timed Skyscraper', 'Detective Conan Movie 07: Crossroad in the Ancient Capital', 'Gundam Build Fighters', 'Hetalia: The Beautiful World', 'Initial D Third Stage', 'Kuroko no Basket 3rd Season NG-shuu', 'Neko no Ongaeshi', 'Seihou Bukyou Outlaw Star', 'White Album 2', 'Working&#039;!!', 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri', 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season', 'Ghost Hunt', 'Gungrave', 'Jungle wa Itsumo Hare nochi Guu', 'Kuroko no Basket 2nd Season NG-shuu', 'Kyou kara Maou! 3rd Series', 'Lupin III (2015)', 'Madang-Eul Naon Amtalg', 'Maria-sama ga Miteru 4th', 'Musekinin Kanchou Tylor', 'Ookami to Koushinryou II: Ookami to Kohakuiro no Yuuutsu', 'Saint Seiya: Meiou Hades Meikai-hen', 'Saint☆Oniisan (Movie)', 'Seikai no Senki II', 'Top wo Nerae! Gunbuster', 'Toshokan Sensou: Kakumei no Tsubasa', 'Uchouten Kazoku', 'Baby Steps', 'Break Blade 5: Shisen no Hate', 'Code Geass: Hangyaku no Lelouch R2 Special Edition Zero Requiem', 'Goku Sayonara Zetsubou Sensei', 'Jormungand', 'Kindaichi Shounen no Jikenbo (TV)', 'Mobile Suit Gundam: Iron-Blooded Orphans', 'Shin Mazinger Shougeki! Z-hen', 'Tentai Senshi Sunred', 'Yuusha-Ou GaoGaiGar', 'Bleach', 'Chuunibyou demo Koi ga Shitai!', 'City Hunter 3', 'Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen', 'Detective Conan Movie 08: Time Travel of the Silver Sky', 'Detective Conan OVA 10: Kid in Trap Island', 'Dragon Ball Kai', 'Hetalia World Series', 'Jungle wa Itsumo Hare nochi Guu Deluxe', 'Kami nomi zo Shiru Sekai', 'Kyousou Giga (TV)', 'Magic Kaito 1412', 'Nejimaki Seirei Senki: Tenkyou no Alderamin', 'Plastic Memories', 'Psycho-Pass Movie', 'Seto no Hanayome', 'Sidonia no Kishi: Daikyuu Wakusei Seneki', 'Tanoshii Muumin Ikka', 'Tasogare Otome x Amnesia', 'Vampire Hunter D (2000)', 'Yuru Yuri Nachuyachumi!', 'Break Blade 3: Kyoujin no Ato', 'Danshi Koukousei no Nichijou Specials', 'Detective Conan Movie 09: Strategy Above the Depths', 'Detective Conan Movie 12: Full Score of Fear', 'Final Fantasy VII: Advent Children', 'Free!: Eternal Summer', 'Hakuouki Movie 1: Kyoto Ranbu', 'Hidamari Sketch x ☆☆☆ Specials', 'K: Missing Kings', 'Last Exile', 'Little Busters!: EX', 'Mobile Suit Gundam Wing: Endless Waltz Movie', 'Naruto: Shippuuden', 'Pokemon: The Origin', 'Yuru Yuri♪♪', 'Zan Sayonara Zetsubou Sensei Bangaichi', '3-gatsu no Lion', '91 Days', 'Akagami no Shirayuki-hime', 'Drifters', 'Gake no Ue no Ponyo', 'Ghost in the Shell 2: Innocence', 'Haikyuu!! Movie 1: Owari to Hajimari', 'Haikyuu!! OVA', 'Hoozuki no Reitetsu OVA', 'Keroro Gunsou', 'Lupin III: Part II', 'Macross F Movie 1: Itsuwari no Utahime', 'Mobile Suit Gundam Seed', 'Nodame Cantabile Finale Special', 'Paradise Kiss', 'Saint Seiya: The Hades Chapter Sanctuary - Yomigaerishi Gold Saint-tachi no Shinwa', 'Saraiya Goyou', 'Shiki Specials', 'Slayers Try', 'To LOVE-Ru Darkness 2nd Specials', 'Transformers the Movie', 'Uchuu Senkan Yamato 2199: Hoshimeguru Hakobune', 'Wolf&#039;s Rain', 'Akatsuki no Yona OVA', 'Ao no Exorcist', 'Claymore', 'Detective Conan: Episode One - Chiisaku Natta Meitantei', 'Ghost in the Shell: Stand Alone Complex - Solid State Society 3D', 'Golden Time', 'Hadashi no Gen', 'Hayate no Gotoku!!', 'Jinrui wa Suitai Shimashita', 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Kako-hen - Yakusoku no Kizuna', 'Little Witch Academia: Mahoujikake no Parade', 'Lucky☆Star: Original na Visual to Animation', 'New Initial D Movie: Legend 1 - Kakusei', 'Pandora Hearts', 'Rurouni Kenshin DVD-BOX Special Ending', 'Berserk: Ougon Jidai-hen I - Haou no Tamago', 'Capeta', 'Charlotte', 'City Hunter &#039;91', 'Kino no Tabi: Nanika wo Suru Tame ni - Life Goes On.', 'Lupin the IIIrd: Jigen Daisuke no Bohyou', 'Master Keaton OVA', 'Mobile Suit Gundam Thunderbolt: December Sky', 'Nisekoi', 'Pokemon XY&amp;Z', 'To LOVE-Ru Darkness 2nd OVA', 'Yamada-kun to 7-nin no Majo (TV)', 'Aoi Bungaku Series', 'Arashi no Yoru ni', 'Bokura wa Minna Kawaisou', 'Chi&#039;s Sweet Home: Atarashii Ouchi', 'Densetsu Kyojin Ideon: Hatsudou-hen', 'Ginga Tetsudou 999', 'Hana yori Dango', 'Hanasakeru Seishounen', 'Hidamari Sketch x 365', 'Hidamari Sketch x SP', 'Ie Naki Ko', 'Michiko to Hatchin', 'New Initial D Movie: Legend 2 - Tousou', 'Persona 3 the Movie 2: Midsummer Knight&#039;s Dream', 'Sexy Commando Gaiden: Sugoiyo!! Masaru-san', 'Tegamibachi Reve

In [15]:
# getting the movie name from the user

anime_name = input(' Enter your favourite anime name : ')

 Enter your favourite anime name :  One Piece

In [16]:
# finding the close match for the movie name given by the user
import difflib
find_close_match=difflib.get_close_matches(anime_name,list_of_all_titles)
print(find_close_match)

['One Piece', 'One Piece Recap', 'Piece']

In [17]:
close_match=find_close_match[0]
print(close_match)

One Piece

In [18]:
# finding the index of the movie with title

index_of_the_movie=movies_data[movies_data.name==close_match]['index'].values[0]
print(index_of_the_movie)

74

In [19]:
# getting a list of similar movies

similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.1260902209026329), (1, 0.5307065454373954), (2, 0.2558960148133461), (3, 0.07032648284190052), (4, 0.2558960148133461), (5, 0.38125090199796524), (6, 0.8769467480520614), (7, 0.10585999463398856), (8, 0.20157164853758006), (9, 0.2558960148133461), (10, 0.25308288666361456), (11, 0.3102915199472872), (12, 0.2558960148133461), (13, 0.6028215881151813), (14, 0.38125090199796524), (15, 0.2828315833923649), (16, 0.3153870664383824), (17, 0.1973642861089956), (18, 0.11501375995211348), (19, 0.5091683355581976), (20, 0.4279971476986122), (21, 0.14133163895529283), (22, 0.4058631820508396), (23, 0.527676856490884), (24, 0.4283565284215892), (25, 0.04905246179470907), (26, 0.10560159948466796), (27, 0.1973642861089956), (28, 0.1973642861089956), (29, 0.34014158071951694), (30, 0.33440433841930284), (31, 0.24390790025865558), (32, 0.4279971476986122), (33, 0.14643910435383253), (34, 0.24390790025865558), (35, 0.3910378381796876), (36, 0.24546340443476106), (37, 0.07674259255413259), (38, 0.1124402442910122), (39, 0.46994451862632514), (40, 0.04764560140508481), (41, 0.08041276977882846), (42, 0.44006896789001243), (43, 0.38125090199796524), (44, 0.4279971476986122), (45, 0.1574609871105785), (46, 0.24390790025865558), (47, 0.06580053723153277), (48, 0.14523858083018376), (49, 0.0600097223663594), (50, 0.0693656421210479), (51, 0.27293360019633145), (52, 0.149735667831387), (53, 0.15727161162947756), (54, 0.24441442642390926), (55, 0.47576041587547113), (56, 0.24390790025865558), (57, 0.18389557836773976), (58, 0.28356801657455183), (59, 0.0), (60, 0.12049553343627813), (61, 0.2333365183637871), (62, 0.18859969506768856), (63, 0.20157164853758006), (64, 0.5572166945424225), (65, 0.20157164853758006), (66, 0.06304963725691645), (67, 0.2106567504462638), (68, 0.16969107332833083), (69, 0.09848415946574668), (70, 0.15233173857155505), (71, 0.16231171985425993), (72, 0.28356801657455183), (73, 0.27750787718795705), (74, 1.0000000000000002), (75, 0.10951822227776416), (76, 0.5958791980917292), (77, 0.07149153631369856), (78, 0.1534482983071659), (79, 0.38125090199796524), (80, 0.05905878690234336), (81, 0.0), (82, 0.2104104419962258), (83, 0.19453531243463296), (84, 0.1872846150857191), (85, 0.14523858083018376), (86, 0.9307920610777507), (87, 0.46994451862632514), (88, 0.24789172377039465), (89, 0.094738949171527), (90, 0.10432934694044059), (91, 0.15778386887946916), (92, 0.17947779202997968), (93, 0.12201342406517075), (94, 0.362080468167106), (95, 0.3447958215310287), (96, 0.14970264924307355), (97, 0.13174636683258978), (98, 0.1357836839095155), (99, 0.14811771217214895), (100, 0.28356801657455183), (101, 0.5374994029134763), (102, 0.09226101444971897), (103, 0.22290966248202992), (104, 0.39126542256175406), (105, 0.2333365183637871), (106, 0.21009281158548745), (107, 0.09226101444971897), (108, 0.31545305002380913), (109, 0.12237488650679795), (110, 0.4490863777285302), (111, 0.2564681977936976), (112, 0.8769467480520614), (113, 0.47123704279919243), (114, 0.14885015118077918), (115, 0.2206069838271227), (116, 0.11872308703958023), (117, 0.3402185663778045), (118, 0.28607355254224703), (119, 0.2667910144693694), (120, 0.3201017500343395), (121, 0.27710057447056197), (122, 0.28356801657455183), (123, 0.17122624312194232), (124, 0.32058350232136396), (125, 0.21496068511929323), (126, 0.0), (127, 0.40409408502117583), (128, 0.4912348452803589), (129, 0.0), (130, 0.09069630901712485), (131, 0.12095062443849663), (132, 0.24009378818953309), (133, 0.5638268578835356), (134, 0.15393635451478888), (135, 0.2781079668178111), (136, 0.18214218102486546), (137, 0.21181813993976373), (138, 0.40409408502117583), (139, 0.4279971476986122), (140, 0.1736747266926463), (141, 0.47420085728087025), (142, 0.24390790025865558), (143, 0.6503159653485232), (144, 0.05386433415850793), (145, 0.8070823784778529), (146, 0.8070823784778529), (147, 0.22752682547874958), (148, 0.4279971476986122), (149, 0.06580053723153277), (150, 0.3286717567572674), (151, 0.31472200407677003), (152, 0.17896587598258595), (153, 0.379666346219142), (154, 0.16576037573880203), (155, 0.18470361600150895), (156, 0.2553533688723409), (157, 0.2834888106229423), (158, 0.2179751964318882), (159, 0.3696034931234446), (160, 0.059417197274181884), (161, 0.07305658414189409), (162, 0.22291859829239027), (163, 0.6503159653485232), (164, 0.11697962230329052), (165, 0.20000807423746716), (166, 0.18746800107127815), (167, 0.11176391384264728), (168, 0.16132120103634978), (169, 0.0), (170, 0.22996032560334054), (171, 0.13383906397914702), (172, 0.17506546007118787), (173, 0.42329668463579034), (174, 0.14894227720793812), (175, 0.8546879718194256), (176, 0.31605939825284446), (177, 0.32058350232136396), (178, 0.7857782129325024), (179, 0.2438633128086908), (180, 0.20135182468886592), (181, 0.22290966248202992), (182, 0.5817926045538719), (183, 0.3588456972731693), (184, 0.36654888379057915), (185, 0.2438633128086908), (186, 0.0959777810133658), (187, 0.10261698354947783), (188, 0.4279971476986122), (189, 0.11491846869985826), (190, 0.057757956918373744), (191, 0.06413547421301175), (192, 0.056895261844823214), (193, 0.22591428818167336), (194, 0.6911005738891141), (195, 0.4053831429604083), (196, 0.0), (197, 0.216469904785833), (198, 0.2772260321062618), (199, 0.1286324394269962), (200, 0.5659335010140945), (201, 0.050205092693462766), (202, 0.8070823784778529), (203, 0.07356084386746597), (204, 0.12201342406517075), (205, 0.20000807423746716), (206, 0.7443184870104809), (207, 0.31944707769224634), (208, 0.14584953395983918), (209, 0.2879132803016161), (210, 0.40177727473527697), (211, 0.21080797383836697), (212, 0.6503159653485232), (213, 0.299904698685741), (214, 0.2957633698727486), (215, 0.0), (216, 0.1997461788107664), (217, 0.09226101444971897), (218, 0.340469055202959), (219, 0.29904061938040316), (220, 0.07858807234849938), (221, 0.27293360019633145), (222, 0.22690674038037217), (223, 0.20135182468886592), (224, 0.24448353028233402), (225, 0.08371266757624675), (226, 0.1234830513023164), (227, 0.20000807423746716), (228, 0.050205092693462766), (229, 0.060040715763753416), (230, 0.17605644704134538), (231, 0.9187795787027142), (232, 0.30034536566656866), (233, 0.25853235634257493), (234, 0.2341925483944678), (235, 0.20063986523116983), (236, 0.2823496609068904), (237, 0.4279971476986122), (238, 0.1445249513500967), (239, 0.3802840083191171), (240, 0.0927866030037615), (241, 0.9187795787027142), (242, 0.18023514899460175), (243, 0.14367552074786177), (244, 0.22540474106207484), (245, 0.09046816705099889), (246, 0.0), (247, 0.0), (248, 0.1424595079109498), (249, 0.2865301889030174), (250, 0.0650739176026597), (251, 0.5827439674034361), (252, 0.32477455253024273), (253, 0.25708867573886174), (254, 0.28356801657455183), (255, 0.5767111731857648), (256, 0.2294591075506214), (257, 0.5572166945424225), (258, 0.23729819191329968), (259, 0.1145754680702059), (260, 0.28624076183285535), (261, 0.34436046293662864), (262, 0.17606037379996028), (263, 0.2176137158826511), (264, 0.340469055202959), (265, 0.14023610142940213), (266, 0.1534482983071659), (267, 0.10499472150986346), (268, 0.5374994029134763), (269, 0.22287068751936598), (270, 0.06859112105789116), (271, 0.5817926045538719), (272, 0.4430995801166635), (273, 0.4338116170611565), (274, 0.25708867573886174), (275, 0.18746800107127815), (276, 0.05715710258366024), (277, 0.26309199239087816), (278, 0.18982805611859394), (279, 0.33106989325881553), (280, 0.2176137158826511), (281, 0.7177621871760872), (282, 0.16386430315223566), (283, 0.09485120093012502), (284, 0.2766897061437433), (285, 0.0), (286, 0.41492642936642776), (287, 0.2564681977936976), (288, 0.5767111731857648), (289, 0.0), (290, 0.5374994029134763), (291, 0.2818353691222551), (292, 0.20188777558719756), (293, 0.25708867573886174), (294, 0.10432934694044059), (295, 0.3207441828744841), (296, 0.1774372953415403), (297, 0.16616749766894529), (298, 0.22287068751936598), (299, 0.15393635451478888), (300, 0.15393635451478888), (301, 0.44006896789001243), (302, 0.20364400765031665), (303, 0.20649517819405022), (304, 0.6088806213935694), (305, 0.08260270128877466), (306, 0.1997461788107664), (307, 0.41890961506284924), (308, 0.2525723864131886), (309, 0.18859969506768856), (310, 0.4602414772146671), (311, 0.27155559761226905), (312, 0.11259399878882091), (313, 0.34564763462583076), (314, 0.2863471098817921), (315, 0.05905117829246185), (316, 0.13387321559014823), (317, 0.059069616874303114), (318, 0.25356537419426606), (319, 0.06097299268484978), (320, 0.14001308779318802), (321, 0.3926035405051216), (322, 0.37687724561394786), (323, 0.19309436811981615), (324, 0.2438633128086908), (325, 0.22234490084753225), (326, 0.2823496609068904), (327, 0.0), (328, 0.15292478377237476), (329, 0.27498651972926763), (330, 0.13324446811844404), (331, 0.22690674038037217), (332, 0.20000807423746716), (333, 0.7403974290682107), (334, 0.0488786038895544), (335, 0.06434781000128223), (336, 0.18012612593294558), (337, 0.1700126925327497), (338, 0.06097299268484978), (339, 0.47123704279919243), (340, 0.2080414775382822), (341, 0.15368576554270527), (342, 0.3987558697946259), (343, 0.187470243759447), (344, 0.25708867573886174), (345, 0.25708867573886174), (346, 0.7011439568297201), (347, 0.23286497127737477), (348, 0.340469055202959), (349, 0.38611295406373336), (350, 0.2607641818196247), (351, 0.3667135804804981), (352, 0.8861638360896128), (353, 0.2453451363018661), (354, 0.05877469257404204), (355, 0.6598967027214425), (356, 0.24490757865358287), (357, 0.4279971476986122), (358, 0.1554209505589856), (359, 0.12601740882725232), (360, 0.18746800107127815), (361, 0.21621871061170128), (362, 0.0), (363, 0.32704715034154846), (364, 0.29242127816602814), (365, 0.0698016360685093), (366, 0.20424932385304326), (367, 0.3092059774385021), (368, 0.340469055202959), (369, 0.3254323997616672), (370, 0.10379090168485307), (371, 0.647644817551041), (372, 0.2176137158826511), (373, 0.11759812950083484), (374, 0.4290732417239831), (375, 0.177000344107548), (376, 0.32743902753977117), (377, 0.20887105704823833), (378, 0.25708867573886174), (379, 0.4867026241165975), (380, 0.1887034099506632), (381, 0.45989249303577323), (382, 0.20063986523116983), (383, 0.11096855807365968), (384, 0.18773595980890037), (385, 0.37047738404542363), (386, 0.2650863731290501), (387, 0.19367168911867444), (388, 0.13543601956019663), (389, 0.09941644075002073), (390, 0.40211113861495223), (391, 0.18746800107127815), (392, 0.22019270191265033), (393, 0.06413547421301175), (394, 0.10200576044330963), (395, 0.2782359865259292), (396, 0.2176137158826511), (397, 0.24448353028233402), (398, 0.4614509486721714), (399, 0.20776595199403514), (400, 0.6815867873413666), (401, 0.29904061938040316), (402, 0.39742433051905607), (403, 0.15393635451478888), (404, 0.31294193354130667), (405, 0.18859969506768856), (406, 0.16386430315223566), (407, 0.18100117209033806), (408, 0.19197682121565957), (409, 0.07978610772564039), (410, 0.216469904785833), (411, 0.11479595204501934), (412, 0.07600677924597134), (413, 0.10585999463398856), (414, 0.06507618647388053), (415, 0.20943026306565177), (416, 0.7631322746253761), (417, 0.21074219595448684), (418, 0.13174636683258978), (419, 0.2772260321062618), (420, 0.5111620783952435), (421, 0.2728410805112796), (422, 0.07428907305319618), (423, 0.14224195518166588), (424, 0.18943727364875984), (425, 0.20685242926765646), (426, 0.27498651972926763), (427, 0.537450191051965), (428, 0.23923158354510207), (429, 0.06591629148123944), (430, 0.4940317775221998), (431, 0.320987143209293), (432, 0.19378807095481898), (433, 0.4059339475997165), (434, 0.22261471553757822), (435, 0.16809548430539317), (436, 0.0587203962389251), (437, 0.340469055202959), (438, 0.23754465682548165), (439, 0.25745272056156754), (440, 0.5886645368553122), (441, 0.1931359964932813), (442, 0.2238903434408328), (443, 0.1966407681516435), (444, 0.11875094952017529), (445, 0.20527508384265936), (446, 0.4443424182473418), (447, 0.5528369056007563), (448, 0.24146034181345752), (449, 0.19653419709748277), (450, 0.0), (451, 0.08244086227379838), (452, 0.13174636683258978), (453, 0.11259399878882091), (454, 0.2602515483987577), (455, 0.28199554917096814), (456, 0.11787189163572054), (457, 0.18313296351567526), (458, 0.37919699430161297), (459, 0.06656858294744203), (460, 0.06591629148123944), (461, 0.45878990192275815), (462, 0.1728497102915489), (463, 0.4602414772146671), (464, 0.3092059774385021), (465, 0.24196150126717458), (466, 0.0930969460022413), (467, 0.16231171985425993), (468, 0.21391263851709236), (469, 0.212283147010494), (470, 0.4178126029296312), (471, 0.07583166258578847), (472, 0.31168619465409647), (473, 0.1145754680702059), (474, 0.17595278308435144), (475, 0.45886874657422116), (476, 0.31080910761023073), (477, 0.07954565872293001), (478, 0.197796373268608), (479, 0.3347336974437012), (480, 0.6911005738891141), (481, 0.31205726849915616), (482, 0.35992650726658454), (483, 0.30362150333240207), (484, 0.15188871188103176), (485, 0.09563498672782933), (486, 0.5833927601016989), (487, 0.0), (488, 0.15039336145693438), (489, 0.06614506890931864), (490, 0.224194109596585), (491, 0.3583430160133579), (492, 0.2294591075506214), (493, 0.24851946985277498), (494, 0.2667910144693694), (495, 0.4270496450558704), (496, 0.3184833515850018), (497, 0.15613647376510909), (498, 0.12123403705895155), (499, 0.4640330475039739), (500, 0.1528262873593146), (501, 0.061237877680088273), (502, 0.1528262873593146), (503, 0.3226200854229284), (504, 0.14210747784911246), (505, 0.14232879743693144), (506, 0.07149153631369856), (507, 0.11875094952017529), (508, 0.3491928266890626), (509, 0.3588456972731693), (510, 0.22718514243199153), (511, 0.050205092693462766), (512, 0.06745491960513904), (513, 0.6984422603312093), (514, 0.0), (515, 0.7443184870104809), (516, 0.14811771217214895), (517, 0.13174636683258978), (518, 0.20135182468886592), (519, 0.4443424182473418), (520, 0.10499472150986346), (521, 0.6083886140850083), (522, 0.1528262873593146), (523, 0.40211113861495223), (524, 0.25708867573886174), (525, 0.07424430876899511), (526, 0.6145642164624339), (527, 0.06336502835934531), (528, 0.22788152239308201), (529, 0.149735667831387), (530, 0.28197746731672363), (531, 0.0853608426913564), (532, 0.1568869132625988), (533, 0.0), (534, 0.405250854113808), (535, 0.3097062411405339), (536, 0.18100117209033806), (537, 0.13174636683258978), (538, 0.31889336789681894), (539, 0.16124659824903734), (540, 0.1348563078884572), (541, 0.05155973114422575), (542, 0.16231171985425993), (543, 0.6146386828143358), (544, 0.25708867573886174), (545, 0.25708867573886174), (546, 0.1912682685637313), (547, 0.0593489950628255), (548, 0.16037491428213332), (549, 0.07880631678777456), (550, 0.4519552827502438), (551, 0.3177668419926694), (552, 0.16836423505059517), (553, 0.14811771217214895), (554, 0.4163904097994108), (555, 0.4163904097994108), (556, 0.11077472647549305), (557, 0.6518632124009238), (558, 0.13174636683258978), (559, 0.07880631678777456), (560, 0.36368088863297005), (561, 0.6088806213935694), (562, 0.39399307548629825), (563, 0.043947041759324804), (564, 0.10504448415849071), (565, 0.13124895476465046), (566, 0.6933690000564406), (567, 0.05522146923814979), (568, 0.13785417257194565), (569, 0.29380684920919914), (570, 0.16264214969168278), (571, 0.34771903169457063), (572, 0.20649517819405022), (573, 0.22183758270894155), (574, 0.5272131554381346), (575, 0.06838682621652795), (576, 0.3347336974437012), (577, 0.2646345621355447), (578, 0.2525723864131886), (579, 0.7459585919087581), (580, 0.5528369056007563), (581, 0.3234172176333282), (582, 0.7797362409668244), (583, 0.2179751964318882), (584, 0.40211113861495223), (585, 0.13921294338606977), (586, 0.13413751397868348), (587, 0.2602515483987577), (588, 0.7443184870104809), (589, 0.0593489950628255), (590, 0.06631047374218339), (591, 0.24448353028233402), (592, 0.362080468167106), (593, 0.45989249303577323), (594, 0.4163904097994108), (595, 0.226660239313734), (596, 0.0779947262303981), (597, 0.13664108385793666), (598, 0.13710639963271468), (599, 0.3131070445958614), (600, 0.16082582193430212), (601, 0.22517970919877364), (602, 0.04555828412190523), (603, 0.3097062411405339), (604, 0.17101828178427997), (605, 0.25708867573886174), (606, 0.25708867573886174), (607, 0.7291849342617622), (608, 0.11452569774756452), (609, 0.14232879743693144), (610, 0.05715710258366024), (611, 0.5990871179120301), (612, 0.3418291234797192), (613, 0.14001308779318802), (614, 0.1641488683789208), (615, 0.6404322595209482), (616, 0.41030853096733744), (617, 0.09563498672782933), (618, 0.06838682621652795), (619, 0.14740024976718952), (620, 0.3619785657629869), (621, 0.3254323997616672), (622, 0.3384936808803022), (623, 0.3402185663778045), (624, 0.0), (625, 0.3027956244802047), (626, 0.17112172594361189), (627, 0.22864301606253226), (628, 0.33315326119053257), (629, 0.6088806213935694), (630, 0.06591629148123944), (631, 0.21117063271774422), (632, 0.04900121228962142), (633, 0.18229509149409978), (634, 0.27332475645520127), (635, 0.06507618647388053), (636, 0.0), (637, 0.42141637280088595), (638, 0.14175430948825388), (639, 0.13191977768842125), (640, 0.1774372953415403), (641, 0.44696987791364107), (642, 0.306814550786803), (643, 0.3757931628325441), (644, 0.7578038165136026), (645, 0.2536937932565633), (646, 0.0), (647, 0.16055831259571166), (648, 0.16231171985425993), (649, 0.2006760560856498), (650, 0.3049403674956417), (651, 0.0), (652, 0.28197746731672363), (653, 0.05054998630457467), (654, 0.07293671879384084), (655, 0.40195219327786014), (656, 0.0), (657, 0.2265294051289098), (658, 0.17911094487533513), (659, 0.7004397842474117), (660, 0.40211113861495223), (661, 0.4519552827502438), (662, 0.39360724001223546), (663, 0.14194722777833435), (664, 0.1641488683789208), (665, 0.24672994272198945), (666, 0.5172835535883886), (667, 0.14452657472952218), (668, 0.20150083293267318), (669, 0.13714103901662164), (670, 0.4993465316887994), (671, 0.12095062443849663), (672, 0.13400640072984926), (673, 0.10964190297367098), (674, 0.292767662473263), (675, 0.19958956433590896), (676, 0.22660810228125655), (677, 0.13174636683258978), (678, 0.05715710258366024), (679, 0.25003266996294365), (680, 0.4669725808941048), (681, 0.0), (682, 0.2080414775382822), (683, 0.22014400350194155), (684, 0.4836342467984437), (685, 0.19727260425664161), (686, 0.19339952423887938), (687, 0.5172835535883886), (688, 0.10204832845069148), (689, 0.24726821023485773), (690, 0.42329668463579034), (691, 0.30425413138551316), (692, 0.3826392174072223), (693, 0.05140889039420302), (694, 0.11321230279430397), (695, 0.391479034990238), (696, 0.13523617014695513), (697, 0.2377838019205175), (698, 0.4614509486721714), (699, 0.17595278308435144), (700, 0.3637332826838969), (701, 0.1942644104340992), (702, 0.052118080109194935), (703, 0.30616022745076543), (704, 0.30302595549366423), (705, 0.6162155649315594), (706, 0.2730895923536437), (707, 0.23950442339669942), (708, 0.5133803286294482), (709, 0.1001713299372754), (710, 0.06336502835934531), (711, 0.05140889039420302), (712, 0.3237557803908805), (713, 0.17419717467118706), (714, 0.13790899589293876), (715, 0.12889092162696397), (716, 0.12003490385371039), (717, 0.8649331373586033), (718, 0.18100117209033806), (719, 0.52806709622159), (720, 0.5346222120196749), (721, 0.10012516959836903), (722, 0.13921294338606977), (723, 0.6336298270628051), (724, 0.1665514439805243), (725, 0.07978610772564039), (726, 0.08945184423654548), (727, 0.11759812950083484), (728, 0.4519552827502438), (729, 0.11257151805368518), (730, 0.22287068751936598), (731, 0.16576037573880203), (732, 0.2539494138065659), (733, 0.1784931911130962), (734, 0.16023152395842358), (735, 0.13710639963271468), (736, 0.32743902753977117), (737, 0.2229608150961006), (738, 0.22287068751936598), (739, 0.3338748177126076), (740, 0.6598967027214425), (741, 0.32185579193453084), (742, 0.09

In [20]:
# sorting the movies based on their similarity score

sorted_similar_movies=sorted(similarity_score,key= lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(74, 1.0000000000000002), (86, 0.9307920610777507), (10899, 0.9307920610777507), (231, 0.9187795787027142), (241, 0.9187795787027142), (896, 0.9187795787027142), (352, 0.8861638360896128), (2161, 0.8861638360896128), (3839, 0.8861638360896128), (6, 0.8769467480520614), (112, 0.8769467480520614), (9673, 0.8769467480520614), (941, 0.8762015401836133), (1171, 0.8762015401836133), (1793, 0.8762015401836133), (2202, 0.8762015401836133), (2492, 0.8762015401836133), (2723, 0.8762015401836133), (3202, 0.8762015401836133), (753, 0.865477934309256), (1576, 0.865477934309256), (1795, 0.865477934309256), (1829, 0.865477934309256), (2119, 0.865477934309256), (3264, 0.865477934309256), (717, 0.8649331373586033), (961, 0.8548008389285093), (1069, 0.8548008389285093), (175, 0.8546879718194256), (3533, 0.8439103596554896), (1289, 0.8364740329695322), (1428, 0.8364740329695322), (7125, 0.8264081888078237), (5264, 0.8210167736455589), (2167, 0.8171440848709528), (10398, 0.8154713008877423), (2933, 0.8143307155595502), (3927, 0.8143307155595502), (3984, 0.8143307155595502), (1192, 0.8090764538826071), (821, 0.8077520124364479), (145, 0.8070823784778529), (146, 0.8070823784778529), (202, 0.8070823784778529), (2046, 0.8070823784778529), (4444, 0.8034776510618833), (4548, 0.7999131837217016), (2184, 0.7989652981111091), (3052, 0.7989652981111091), (3289, 0.7989652981111091), (1974, 0.7964657255298968), (2108, 0.7964657255298968), (10458, 0.7964657255298968), (178, 0.7857782129325024), (10901, 0.7857782129325024), (3757, 0.785742012042575), (4521, 0.785742012042575), (1761, 0.7802929897723695), (582, 0.7797362409668244), (1488, 0.7693525214828001), (3520, 0.7690239681935865), (5865, 0.7679937718666597), (416, 0.7631322746253761), (980, 0.7631322746253761), (1499, 0.7631322746253761), (8923, 0.7601442687878963), (11089, 0.7601442687878963), (644, 0.7578038165136026), (995, 0.7577495775050745), (5748, 0.7550798453415788), (6285, 0.7523168799924829), (6594, 0.7464443205048639), (7353, 0.7464443205048639), (579, 0.7459585919087581), (2472, 0.7444185499739768), (206, 0.7443184870104809), (515, 0.7443184870104809), (588, 0.7443184870104809), (1930, 0.7443184870104809), (10121, 0.7424758338691546), (10652, 0.7424758338691546), (4382, 0.7409145637389379), (333, 0.7403974290682107), (2515, 0.7403974290682107), (5785, 0.7396685724524485), (1105, 0.7386608083086643), (4986, 0.7342524769913192), (7386, 0.7293926852854853), (607, 0.7291849342617622), (1333, 0.7284493540241879), (3288, 0.7263565243301484), (830, 0.7256186731136879), (4041, 0.7237279260302827), (5167, 0.7237279260302827), (5556, 0.7211549261417075), (1784, 0.7186322054981924), (2479, 0.7186121446114415), (281, 0.7177621871760872), (3802, 0.7168851011135424), (4200, 0.7168851011135424), (4988, 0.7168851011135424), (10381, 0.7167570372054418), (2965, 0.716132834282494), (3184, 0.716132834282494), (3781, 0.7139465130223093), (1271, 0.7128166004213322), (3543, 0.7128166004213322), (2093, 0.7124069379435936), (4012, 0.7112625886789468), (4785, 0.7073274388591829), (946, 0.706683567256098), (1131, 0.706683567256098), (10907, 0.7052471178825792), (1084, 0.7049841055303314), (6088, 0.704975201398291), (2681, 0.7046678403571152), (2259, 0.7028947695106063), (346, 0.7011439568297201), (659, 0.7004397842474117), (513, 0.6984422603312093), (6293, 0.6955413994702551), (4275, 0.6949097931261125), (3317, 0.694687291051618), (8659, 0.694558599073158), (566, 0.6933690000564406), (3476, 0.6930278388368506), (9575, 0.6930278388368506), (1159, 0.6928701158296509), (3017, 0.6928701158296509), (6199, 0.6924588138701971), (2882, 0.6919863774180512), (194, 0.6911005738891141), (480, 0.6911005738891141), (11034, 0.6911005738891141), (10751, 0.6907852038762835), (1409, 0.6900744946333314), (5999, 0.6900744946333314), (2534, 0.68980817791727), (6121, 0.6897886194290267), (8060, 0.6891172259729768), (7714, 0.6869895547079043), (7419, 0.6859820229264831), (3203, 0.6847992243657334), (4314, 0.6847992243657334), (4404, 0.6833628935967307), (1399, 0.6829833607379581), (6143, 0.6817764909016701), (400, 0.6815867873413666), (2421, 0.6797889424618869), (814, 0.6786119269145823), (996, 0.6786119269145823), (4644, 0.6786119269145823), (3024, 0.6780485084179486), (859, 0.6779907894762018), (5503, 0.6767276153739291), (9844, 0.6767276153739291), (989, 0.6766902868440484), (1853, 0.6766902868440484), (1868, 0.6766902868440484), (3243, 0.6766902868440484), (4595, 0.6766902868440484), (1013, 0.6740510229439625), (1753, 0.6740510229439625), (2232, 0.6740510229439625), (2946, 0.6740510229439625), (978, 0.6689011364709949), (4045, 0.6671967810988011), (10970, 0.6670532984223613), (7122, 0.6666202317105051), (2210, 0.6663221496357186), (8345, 0.6656485493797225), (1796, 0.6644536643233327), (1227, 0.6618445410024622), (10882, 0.6613719838704727), (3022, 0.6604924571386082), (2617, 0.6604889564107531), (355, 0.6598967027214425), (740, 0.6598967027214425), (1956, 0.6598967027214425), (2020, 0.6598967027214425), (4293, 0.6598967027214425), (4413, 0.6598967027214425), (9913, 0.6570131761021687), (9962, 0.6570131761021687), (10350, 0.6570131761021687), (4432, 0.6567174735210077), (5218, 0.6542460651304621), (1244, 0.6540409691539627), (1694, 0.6540409691539627), (5917, 0.6532155939011359), (11012, 0.6525190550154221), (557, 0.6518632124009238), (143, 0.6503159653485232), (163, 0.6503159653485232), (212, 0.6503159653485232), (1729, 0.6483447398248865), (4171, 0.6483447398248865), (10339, 0.6481905300978804), (10370, 0.6481905300978804), (371, 0.647644817551041), (5189, 0.646487055343002), (1931, 0.6459777762542346), (12020, 0.6458887058844), (5308, 0.6448711983662987), (4715, 0.6441500538716992), (4696, 0.6432873720674299), (9891, 0.6417837665603123), (5048, 0.6413216399509155), (1711, 0.6406337628552456), (2838, 0.6406002729197866), (4960, 0.6406002729197866), (5562, 0.6406002729197866), (615, 0.6404322595209482), (841, 0.6404322595209482), (8183, 0.6390098031403431), (960, 0.6377171606401696), (2981, 0.6347756542475285), (1063, 0.6345139039525625), (723, 0.6336298270628051), (815, 0.6303162881578954), (1636, 0.6291596642552932), (1895, 0.6291596642552932), (2311, 0.6291596642552932), (3273, 0.6291596642552932), (5404, 0.6291596642552932), (6911, 0.6291596642552932), (3344, 0.6277859807204254), (4424, 0.626509357583988), (1792, 0.6236171959770633), (3025, 0.6221672953148643), (5517, 0.6210092203021518), (8870, 0.6210092203021518), (8871, 0.6210092203021518), (8872, 0.6210092203021518), (8875, 0.6210092203021518), (8876, 0.6210092203021518), (998, 0.6195318911674492), (6587, 0.6195318911674492), (6183, 0.6192081775136634), (4181, 0.6175782673493628), (5839, 0.6173688912788777), (1079, 0.6171707542928772), (1822, 0.6169111128437397), (705, 0.6162155649315594), (5850, 0.6158073661057797), (543, 0.6146386828143358), (793, 0.6146386828143358), (526, 0.6145642164624339), (4576, 0.6144832108331711), (5239, 0.6137661086764823), (1991, 0.6135967757476186), (9390, 0.6134528795228777), (4066, 0.6127402260921009), (3680, 0.6114261585134898), (3408, 0.6093491238337989), (4375, 0.6089219892823325), (304, 0.6088806213935694), (561, 0.6088806213935694), (629, 0.6088806213935694), (936, 0.6088806213935694), (1569, 0.6088806213935694), (4446, 0.6088806213935694), (5280, 0.6088806213935694), (5716, 0.6088806213935694), (5717, 0.6088806213935694), (5776, 0.6088806213935694), (6032, 0.6088806213935694), (6187, 0.6088806213935694), (6800, 0.6088806213935694), (8497, 0.6088806213935694), (8498, 0.6088806213935694), (10657, 0.6085816562840007), (5571, 0.6084668366757767), (521, 0.6083886140850083), (1459, 0.6083886140850083), (784, 0.608071257634246), (2416, 0.608071257634246), (4071, 0.6069580103122626), (2543, 0.6042827364914114), (3821, 0.6042827364914114), (1184, 0.6042124709876467), (5307, 0.6036166711378265), (2312, 0.6032251985309968), (13, 0.6028215881151813), (1667, 0.6026531123882196), (2187, 0.6026531123882196), (10914, 0.6019519235849303), (966, 0.6017762924648247), (4569, 0.6017762924648247), (4927, 0.6015427326361398), (1263, 0.6013961511568992), (1949, 0.6013961511568992), (6130, 0.6013961511568992), (10551, 0.6004230263799168), (1589, 0.5996905623470519), (3494, 0.5996905623470519), (2035, 0.5993166901829047), (611, 0.5990871179120301), (881, 0.5990871179120301), (944, 0.5990871179120301), (1023, 0.5990871179120301), (1196, 0.5990871179120301), (1478, 0.5990871179120301), (6258, 0.5986489606163617), (7147, 0.5976705639062918), (1791, 0.5967399878526938), (789, 0.5962158428627973), (1096, 0.5962158428627973), (76, 0.5958791980917292), (803, 0.5958791980917292), (1671, 0.5939516471494444), (2940, 0.5939516471494444), (3700, 0.5939516471494444), (3744, 0.5939516471494444), (3857, 0.5939516471494444), (10909, 0.5939516471494444), (845, 0.5929440955722907), (3329, 0.5921788934319185), (3977, 0.5916028558888814), (1397, 0.5909556771443354), (3735, 0.5909556771443354), (5714, 0.5909556771443354), (6350, 0.5909556771443354), (6929, 0.5909556771443354), (10942, 0.5909556771443354), (6716, 0.5897477956235895), (10661, 0.5897477956235895), (440, 0.5886645368553122), (1343, 0.588019732984516), (2264, 0.5876681287641493), (3941, 0.5868347448722171), (3061, 0.5864494564383463), (3455, 0.5839073754866787), (8928, 0.5837872137650637), (10432, 0.5834749223092554), (486, 0.5833927601016989), (1472, 0.5833927601016989), (1573, 0.5833927601016989), (2997, 0.5833927601016989), (4713, 0.583159156482028), (7008, 0.583159156482028), (9009, 0.583159156482028), (251, 0.5827439674034361), (1224, 0.5827439674034361), (3130, 0.5819229671954477), (6015, 0.5818257178111923), (182, 0.5817926045538719), (271, 0.5817926045538719), (1823, 0.579895447067263), (4586, 0.579895447067263), (4966, 0.579895447067263), (10280, 0.579895447067263), (5362, 0.5787048404450981), (1103, 0.5783592072875066), (2458, 0.5783592072875066), (3961, 0.5773722415480878), (4478, 0.5773722415480878), (9896, 0.5773722415480878), (255, 0.5767111731857648), (288, 0.5767111731857648), (2908, 0.5766223242829962), (7867, 0.5762892213722208), (2478, 0.574817891307186), (7310, 0.574817891307186), (10859, 0.5747085256358866), (4414, 0.5741522338602875), (4741, 0.5741522338602875), (4780, 0.5741522338602875), (7451, 0.5740147495369065), (4942, 0.573838651842064), (1827, 0.5737431762274875), (2160, 0.5737431762274875), (2245, 0.5737431762274875), (4440, 0.5737431762274875), (7363, 0.5734303553912062), (1209, 0.5728498019551391), (2615, 0.5728498019551391), (3038, 0.5728498019551391), (1689, 0.5721859641830407), (2692, 0.5721859641830407), (4193, 0.5721859641830407), (4964, 0.5721859641830407), (9684, 0.5713227282689453), (4225, 0.571035144421544), (6331, 0.5706514499396684), (8526, 0.5697501153630298), (3437, 0.5694590461784298), (1887, 0.5685020461391881), (5028, 0.5685020461391881), (8640, 0.5685020461391881), (2494, 0.5682952253743943), (6198, 0.567634477046056), (9601, 0.5667296514949464), (200, 0.5659335010140945), (1237, 0.5650045968062893), (4137, 0.5648620777738336), (4342, 0.5648620777738336), (6251, 0.5648620777738336), (8312, 0.5646670129895188), (10900, 0.5642688912513824), (133, 0.5638268578835356), (1678, 0.5635130294985116), (1454, 0.562105146755567), (3490, 0.5616415901058917), (2135, 0.5616063152718125), (2621, 0.5600836960333981), (5889, 0.5587559655723087), (2992, 0.5585310448074012), (1051, 0.5584091186123726), (64, 0.5572166945424225), (257, 0.5572166945424225), (3007, 0.5569298958694389), (10659, 0.5554607620247644), (6992, 0.5545367421494671), (8191, 0.5537727290069971), (2644, 0.5530281689517864), (10486, 0.5530281689517864), (447, 0.5528369056007563), (580, 0.5528369056007563), (775, 0.5524830535929248), (1301, 0.5524830535929248), (3564, 0.5524830535929248), (8338, 0.5524830535929248), (11085, 0.5524830535929248), (4295, 0.5501305886452589), (2616, 0.5494136843707342), (10915, 0.5494136843707342), (2958, 0.5486828611621475), (4057, 0.5483064715076055), (2269, 0.5476260842413787), (7628, 0.5471827712990438), (8877, 0.5461130318105356), (8878, 0.5461130318105356), (8879, 0.5461130318105356), (10466, 0.5461130318105356), (1909, 0.5453653116693078), (4038, 0.5453361899138313), (4573, 0.5453361899138313), (3228, 0.5451277711646352), (3904, 0.5451277711646352), (4965, 0.5451277711646352), (11087, 0.5451277711646352), (1587, 0.544909482398112), (5067, 0.5446518438168136), (1745, 0.5410523258833879), (5906, 0.5410523258833879), (4808, 0.5405897498707679), (4507, 0.5399611895989832), (3920, 0.5395352915047452), (2342, 0.5392067690781313), (2852, 0.5392067690781313), (6163, 0.5392067690781313), (811, 0.5385276643819523), (10465, 0.538501272052422), (2633, 0.537891814332291), (101, 0.5374994029134763), (268, 0.5374994029134763), (290, 0.5374994029134763), (795, 0.5374994029134763), (10953, 0.5374994029134763), (887, 0.5374706823774957), (427, 0.537450191051965), (4003, 0.5373665247572029), (1374, 0.5371562325044938), (2031, 0.5371293295072155), (4855, 0.5364360903703161), (4902, 0.5364360903703161), (5521, 0.5364360903703161), (5492, 0.5350327784851561), (720, 0.5346222120196749), (1033, 0.5346222120196749), (2151, 0.5333928201099872), (2190, 0.5333928201099872), (2610, 0.5333928201099872), (5637, 0.5333928201099872), (6575, 0.5333928201099872), (1922, 0.5333107264027137), (1794, 0.5322525370906346), (2427, 0.5322525370906346), (9530, 0.5322525370906346), (2811, 0.5307811356882586), (1, 0.5307065454373954), (5974, 0.5301101682138432), (2661, 0.5300043589858657), (6868, 0.5299186920174066), (1844, 0.5295374848935956), (1511, 0.5287906346363818), (1047, 0.5286085358124367), (719, 0.52806709622159), (1479, 0.5280025119566167), (1284, 0.5279096314862742), (1514, 0.5279096314862742), (2057, 0.5279096314862742), (2106, 0.5279096314862742), (2584, 0.5279096314862742), (2839, 0.5279096314862742), (3080, 0.5279096314862742), (3579, 0.5279096314862742), (4495, 0.5279096314862742), (5066, 0.5279096314862742), (5195, 0.5279096314862742), (5365, 0.5279096314862742), (9414, 0.5279096314862742), (23, 0.527676856490884), (10897, 0.527676856490884), (574, 0.5272131554381346), (2685, 0.5251367010568739), (10709, 0.5241756359873259), (3943, 0.5229372366388965), (2959, 0.5227619834160447), (4128, 0.5227619834160447), (2665, 0.522372181178758), (1109, 0.5221250188436848), (4336, 0.5221250188436848), (1781, 0.5220535835584648), (8630, 0.5220037777133426), (3449, 0.5214684306469628), (4527, 0.5211200281365763), (2652, 0.5201312990070985), (4264, 0.5196258474478542), (6970, 0.5186952498600831), (3792, 0.5183003465837521), (666, 0.5172835535883886), (687, 0.5172835535883886), (1508, 0.5172835535883886), (1834, 0.5172835535883886), (2558, 0.5172835535883886), (2656, 0.5172835535883886), (3265, 0.5172835535883886), (4213, 0.5172835535883886), (4214, 0.5172835535883886), (4878, 0.5172835535883886), (5583, 0.5172835535883886), (2075, 0.5164237163038509), (2728, 0.5164237163038509), (3244, 0.5164237163038509), (3495, 0.5164237163038509), (5039, 0.5160795223694832), (5217, 0.515368243056435), (9592, 0.515368243056435), (9683, 0.515368243056435), (8874, 0.5148885087092122), (8882, 0.5148885087092122), (959, 0.5145809312387333), (1854, 0.5145809312387333), (2524, 0.5145809312387333), (3592, 0.5145809312387333), (2239, 0.5143765867491418), (708, 0.5133803286294482), (3196, 0.5124634712419444), (3456, 0.5121317006604776), (5662, 0.5121317006604776), (2234, 0.5121021673410846), (5789, 0.5117053429868731), (420, 0.5111620783952435), (1147, 0.5094159407606433), (2164, 0.5094159407606433), (2807, 0.5094159407606433), (2893, 0.5094159407606433), (4614, 0.5094159407606433), (1071, 0.5092516926860943), (5328, 0.5092105236112678), (19, 0.5091683355581976), (6086, 0.5085505369941948), (10530, 0.5080141152149957), (918, 0.5077722254005459), (1718, 0.5077722254005459), (7144, 0.5077722254005459), (2163, 0.5071764399527818), (4187, 0.5040644744168599), (8049, 0.5038884718355664), (1507, 0.5036592905988686), (11067, 0.5034490500617587), (5673, 0.5020758436726973), (1445, 0.5008886218237247), (6457, 0.5007640057957568), (5648, 0.5001935876626996), (2894, 0.49966378643724935), (1558, 0.4995234971316472), (6206, 0.4994561704395671), (670, 0.4993465316887994), (2701, 0.49931687118104134), (2849, 0.49910379314214715), (4244, 0.49910379314214715), (9096, 0.49910379314214715), (9371, 0.49910379314214715), (4911, 0.4959863330675303), (6491, 0.4959484926360114), (1633, 0.4953164568080063), (2009, 0.4953164568080063), (2241, 0.4953164568080063), (4000, 0.4953164568080063), (4031, 0.4953164568080063), (5649, 0.4953164568080063), (8499, 0.4953164568080063), (5079, 0.4949453131554646), (1630, 0.4946228761194036), (3974, 0.4944983707595224), (885, 0.49431981840720496), (430, 0.4940317775221998), (1597, 0.4940317775221998), (2055, 0.4940317775221998), (2089, 0.4940317775221998), (1053, 0.49290204007142635), (10977, 0.49290204007142635), (4867, 0.4923934644807364), (7736, 0.49150593544644056), (11392, 0.49150449352877246), (5366, 0.4913888007560798), (6095, 0.4913888007560798), (6863, 0.4913888007560798), (128, 0.4912348452803589), (2780, 0.49012513137729896), (3435, 0.49012513137729896), (3604, 0.49012513137729896), (4197, 0.49012513137729896), (8141, 0.49012513137729896), (4816, 0.4892050961708977), (5118, 0.4892050961708977), (5076, 0.4891014542748534), (9739, 0.4879153459519653), (4406, 0.4876124532484756), (2829, 0.4869388791973646), (3091, 0.4869388791973646), (4434, 0.4869388791973646), (379, 0.4867026241165975), (911, 0.4867026241165975), (1135, 0.4867026241165975), (10971, 0.4867026241165975), (11033, 0.4867026241165975), (9740, 0.48542872149868993), (2938, 0.4847580835672012), (1773, 0.4840637425130492), (10800, 0.48403209755978904), (6338, 0.48386330411404743), (6763, 0.48363930538921984), (684, 0.4836342467984437), (943, 0.4836342467984437), (2285, 0.4836342467984437), (2377, 0.4836342467984437), (3159, 0.4836342467984437), (4010, 0.4836342467984437), (1967, 0.48311986833947373), (2761, 0.48254579542285375), (4471, 0.48246323438678007), (2486, 0.48213383984221814), (2116, 0.4814916979010844), (2153, 0.4814916979010844), (2194, 0.4814916979010844), (2272, 0.4814916979010844), (2344, 0.4814916979010844), (2371, 0.4814916979010844), (2487, 0.4814916979010844), (2649, 0.4814916979010844), (2751, 0.4814916979010844), (2795, 0.4814916979010844), (2991, 0.4814916979010844), (3105, 0.4814916979010844), (3173, 0.4814916979010844), (3256, 0.4814916979010844), (3301, 0.4814916979010844), (3500, 0.4814916979010844), (3561, 0.4814916979010844), (3624, 0.4814916979010844), (4160, 0.4814916979010844), (6995, 0.481486360185972), (1965, 0.4807780614501855), (2335, 0.4807780614501855), (2459, 0.4807780614501855), (2657, 0.4807780614501855), (3041, 0.4807780614501855), (3400, 0.4807780614501855), (3532, 0.4807780614501855), (3635, 0.4807780614501855), (3704, 0.4807780614501855), (3953, 0.4807780614501855), (4915, 0.4807780614501855), (4994, 0.4807780614501855), (5230, 0.4807780614501855), (5907, 0.4807780614501855), (6823, 0.4807780614501855), (7003, 0.4807780614501855), (7016, 0.4807780614501855), (8217, 0.4807780614501855), (8363, 0.4807780614501855), (8954, 0.4807780614501855), (9024, 0.4807780614501855), (9332, 0.4807780614501855), (10092, 0.4807780614501855), (10239, 0.4807780614501855), (10670, 0.4807780614501855), (10765, 0.4807780614501855), (10993, 0.4807780614501855), (6229, 0.4802667626213767), (1439, 0.48000317044250684), (2005, 0.48000317044250684), (2386, 0.48000317044250684), (6440, 0.47998502402308374), (5957, 0.4798603055921853), (9259, 0.47926137267917646), (1390, 0.47923556754554125), (5203, 0.4781062162593531), (910, 0.4777316403094116), (3457, 0.4777316403094116), (770, 0.4775811174611764), (1264, 0.47663287046655567), (1603, 0.47663287046655567), (5885, 0.47634107894645566), (5970, 0.47634107894645566), (3523, 0.47602169877729006), (3524, 0.47602169877729006), (3551, 0.47602169877729006), (5923, 0.4760019871370271), (55, 0.47576041587547113), (2821, 0.4754364807341796), (5618, 0.4752459898349866), (3535, 0.4749007655958637), (3443, 0.4746730115

In [21]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['name'].values[0]
  if (i<11):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you :

1 . One Piece
2 . Shingeki no Kyojin
3 . Shingeki no Kyojin Season 2
4 . One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari
5 . One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna
6 . One Piece: Episode of Sabo - 3 Kyoudai no Kizuna Kiseki no Saikai to Uketsugareru Ishi
7 . One Piece Film: Strong World Episode 0
8 . One Piece Recap
9 . One Piece: Taose! Kaizoku Ganzack
10 . Hunter x Hunter (2011)

# Smart Anime Finder

In [26]:
anime_name = input(' Enter your favourite anime name : ')

list_of_all_titles = movies_data['name'].tolist()

find_close_match = difflib.get_close_matches(anime_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.name == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Animes suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['name'].values[0]
  if (i<11):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite anime name :  Death Note

Animes suggested for you :

1 . Death Note
2 . Mousou Dairinin
3 . Death Note Rewrite
4 . Higurashi no Naku Koro ni Kai
5 . Mirai Nikki (TV)
6 . Higurashi no Naku Koro ni Rei
7 . Higurashi no Naku Koro ni
8 . Monster
9 . Mirai Nikki (TV): Ura Mirai Nikki
10 . Zankyou no Terror